### ISSUE TITLE
Shouldn't `taylor_estimates` calculate aggregated ranking instead of ranking of last forward pass?

### ISSUE THREAD

**Issue by vinsis** [alexfjw/prunnable-layers-pytorch#2]
It seems that in [this](https://github.com/alexfjw/prunnable-layers-pytorch/blob/master/prunable_nn.py#L45) line, `taylor_estimates` is overwritten after every pass. But I believe the channel ranking should be based on not just one pass but the average of multiple passes. How is this managed in the current implementation? Is it the case that the logic to calculate aggregate ranking can be implemented outside this model?

Thanks for the code by the way. It's pretty helpful.

**Comment by alexfjw** [comment]
Its been some time since I've written the code so I can't quite recall if the paper asked for an average. You're right though, this implementation only uses the data from one pass. 

A quick look at the paper mentions the following though:

>For a minibatch with T >1 examples, the criterion is computed for each example separately and averaged over T

The minibatch logic is already included, if that's what you're referring to.


> Is it the case that the logic to calculate aggregate ranking can be implemented outside this model?

The logic to calculate ranking is independent of layers. See `models.py` for an example.

**Comment by vinsis** [comment]
Got it. Thanks.
